src/objects/ZZ_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>ZZ Enviroment</label>
    <nameField>
        <label>Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZZ Enviroments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZZ_Enviroment_Release__c.object
<CustomObject>
    <fields>
        <fullName>Enviroment__c</fullName>
        <label>Enviroment</label>
        <referenceTo>ZZ_Enviroment__c</referenceTo>
        <relationshipName>Enviroment_Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>ZZ_Release__c</referenceTo>
        <relationshipName>Enviroment_Releases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ZZ Enviroment Release</label>
    <nameField>
        <displayFormat>EnviromentRelease-{000000}</displayFormat>
        <label>Enviroment Release Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZZ Enviroment Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZZ_Release__c.object
<CustomObject>
    <label>ZZ Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZZ Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZZ_Deployment_StatusTest.cls
@isTest (seeAllData=false)
private class ZZ_Deployment_StatusTest {
	
	@isTest static void shouldNotReturnRecords() {
		ZZ_Deployment_Status ds = new ZZ_Deployment_Status();
        
        System.assertEquals(0, ds.liDeployments.size(), 'No records where created');        
        System.assertEquals(0, ds.liCurrentDeployment.size(), 'No records where created');
        
	}
	@isTest static void shouldReturn1Record() {
        // given
		ZZ_Deployment_Status ds = new ZZ_Deployment_Status();
        ZZ_Enviroment__c env = new ZZ_Enviroment__c (name='Unit Test', Order__c= 99);
        insert env;
        
        ZZ_Release__c rel = new ZZ_Release__c (name='Unit test 1');
        insert rel;
        
        ZZ_Enviroment_Release__c erel = new ZZ_Enviroment_Release__c();
        erel.Enviroment__c = env.id;
        erel.Release__c = rel.id;
        insert erel;
        
        //when
        //then
        System.assertEquals(1, ds.liDeployments.size(), '1 should be returned');        
        System.assertEquals(1, ds.liCurrentDeployment.size(), '1 should be returned');
        
       
	}
	
}