src/objects/ZZ_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>ZZ Enviroment</label>
    <nameField>
        <label>Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZZ Enviroments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZZ_Enviroment_Release__c.object
<CustomObject>
    <fields>
        <fullName>Deployed_Date__c</fullName>
        <label>Deployed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enviroment__c</fullName>
        <label>Enviroment</label>
        <referenceTo>ZZ_Enviroment__c</referenceTo>
        <relationshipName>Enviroment_Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>ZZ_Release__c</referenceTo>
        <relationshipName>Enviroment_Releases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prepared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ZZ Enviroment Release</label>
    <nameField>
        <displayFormat>EnviromentRelease-{000000}</displayFormat>
        <label>Enviroment Release Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZZ Enviroment Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZZ_Release__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ZZ Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZZ Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZZ_Deployment_Status.cls
public without sharing class ZZ_Deployment_Status {
	public ZZ_Deployment_Status() {

	}

	public List <DeploymentWrap> liDeployments {
		get{
			if (liDeployments == null){
				liDeployments = new List <DeploymentWrap>();

				for (ZZ_Enviroment__c env : [select (select Release__r.name, Release__r.description__c,
						Release__c, Status__c, Deployed_Date__c from Enviroment_Releases__r order by name desc), Name, Order__c
					from ZZ_Enviroment__c
					order by Order__c]){
					if (env.Enviroment_Releases__r.size() == 0){
						liDeployments.add(new DeploymentWrap(env.name, null, null, null, null));
					}
					else{
						for (ZZ_Enviroment_Release__c er : env.Enviroment_Releases__r){
							liDeployments.add(new DeploymentWrap(env.name, er.Release__r.name, er.Release__r.description__c, er.Status__c, er.Deployed_Date__c));
						}
					}
				}
			}
			return liDeployments;
		}
		set;
	}

	public List <DeploymentWrap> liCurrentDeployment {
		get{
			if (liCurrentDeployment == null){
				liCurrentDeployment = new List <DeploymentWrap>();

				for (ZZ_Enviroment__c env : [select (select Release__r.name, Release__r.description__c,
						Release__c, Status__c,Deployed_Date__c  from Enviroment_Releases__r order by name desc), Name, Order__c
					from ZZ_Enviroment__c
					order by Order__c]){
					if (env.Enviroment_Releases__r.size() == 0){
						liCurrentDeployment.add(new DeploymentWrap(env.name, null, null, null, null));
					}
					else{
						ZZ_Enviroment_Release__c er = env.Enviroment_Releases__r[0];
						liCurrentDeployment.add(new DeploymentWrap(env.name, er.Release__r.name, er.Release__r.description__c, er.Status__c, er.Deployed_Date__c));
					}
				}
			}
			return liCurrentDeployment;
		}
		set;
	}

	public class DeploymentWrap{
		public String enviromentName {get;set;}
		public String deploymentName {get;set;}
		public String deploymentDesc {get;set;}
		public String status {get;set;}
		public Date deployDate {get;set;}

		public DeploymentWrap(){}
		public DeploymentWrap (String env, String deploy, String description, String deploymentStatus, Date dDate){
			this.enviromentName = env;
			this.deploymentName = deploy;
			this.deploymentDesc = description;
			this.status = deploymentStatus;
			this.deployDate = dDate;
		}
	}
}